
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author HP
 */
public class project3 extends javax.swing.JFrame {

    /**
     * Creates new form project3
     */
    String path;

    public project3() {
        initComponents();
        setSize(600, 500);
        setTitle("Add Employee ");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        lb23 = new javax.swing.JLabel();
        lb4 = new javax.swing.JLabel();
        lb5 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        tf3 = new javax.swing.JTextField();
        tf4 = new javax.swing.JTextField();
        bt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tf5 = new javax.swing.JTextField();
        bt5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        lb1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lb1.setForeground(new java.awt.Color(255, 255, 51));
        lb1.setText("ADD  EMPLOYEE");
        getContentPane().add(lb1);
        lb1.setBounds(140, 10, 170, 40);

        lb2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lb2.setText("Username");
        getContentPane().add(lb2);
        lb2.setBounds(110, 80, 80, 20);

        lb23.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lb23.setText("Name");
        getContentPane().add(lb23);
        lb23.setBounds(110, 120, 50, 20);

        lb4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lb4.setText("Email");
        getContentPane().add(lb4);
        lb4.setBounds(110, 160, 50, 20);

        lb5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lb5.setText("Phone");
        getContentPane().add(lb5);
        lb5.setBounds(110, 200, 50, 20);

        tf1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tf1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(53, 255, 255)));
        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        getContentPane().add(tf1);
        tf1.setBounds(200, 70, 140, 30);

        tf2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tf2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(53, 255, 255)));
        tf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf2ActionPerformed(evt);
            }
        });
        getContentPane().add(tf2);
        tf2.setBounds(200, 110, 140, 30);

        tf3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tf3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(53, 255, 255)));
        tf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf3ActionPerformed(evt);
            }
        });
        getContentPane().add(tf3);
        tf3.setBounds(200, 150, 140, 30);

        tf4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tf4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(53, 255, 255)));
        tf4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf4ActionPerformed(evt);
            }
        });
        getContentPane().add(tf4);
        tf4.setBounds(200, 190, 140, 30);

        bt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bt.setForeground(new java.awt.Color(0, 0, 204));
        bt.setText("ADD");
        bt.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(53, 255, 255)));
        bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActionPerformed(evt);
            }
        });
        getContentPane().add(bt);
        bt.setBounds(160, 320, 120, 50);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Add Photo");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 230, 80, 40);

        tf5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tf5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(53, 255, 255)));
        tf5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf5ActionPerformed(evt);
            }
        });
        getContentPane().add(tf5);
        tf5.setBounds(200, 230, 140, 30);

        bt5.setBackground(new java.awt.Color(0, 0, 204));
        bt5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bt5.setText("BROWSE");
        bt5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(53, 255, 255)));
        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt5ActionPerformed(evt);
            }
        });
        getContentPane().add(bt5);
        bt5.setBounds(360, 230, 100, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 520, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed

    }//GEN-LAST:event_tf1ActionPerformed

    private void tf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf2ActionPerformed

    private void tf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf3ActionPerformed

    private void tf4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf4ActionPerformed

    private void btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActionPerformed
        // TODO add your handling code here:
        try {
            tf1.requestFocus();
            Class.forName("com.mysql.jdbc.Driver");
            System.out.println("Driver loaded");
            Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/test", "root", "system27");
            System.out.println("Connection with DataBase successful");

            Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String s = tf1.getText();
            String s2 = tf2.getText();
            String s3 = tf3.getText();
            String s4 = tf4.getText();

            try {
                FileInputStream fis = new FileInputStream(path);
                FileOutputStream fos = new FileOutputStream(System.getProperty("user.home") + "\\images\\" + s + ".jpg");

                byte b[] = new byte[1000];

                int r;
                while (true) {
                    r = fis.read(b, 0, 1000);

                    if (r == -1) {
                        break;
                    }

                    fos.write(b, 0, r);

                }
                fis.close();
                fos.close();
                System.out.println("File copied successfully");
                tf5.setText("");

            } catch (Exception ex) {
                ex.printStackTrace();

            }

            if (s.equals("") || s2.equals("") || s3.equals("") || s4.equals("")) {
                JOptionPane.showMessageDialog(this, "All fields must be filled");
            } else {
                ResultSet rs = stmt.executeQuery("select * from employee where username = '" + s + "'");

                System.out.println("ResultSet created");

                if (rs.next()) {
                    JOptionPane.showMessageDialog(this, "Employee already exists");

                } else {
                    rs.moveToInsertRow();
                    System.out.println(rs);
                    rs.updateString("username", s);
                    rs.updateString("name", s2);
                    rs.updateString("email", s3);
                    rs.updateString("phone", s4);

                    int n = (int) (10000 + ((99999 - 10000) * Math.random()));
                    rs.updateString("password", n + "");
                    rs.insertRow();

                    JOptionPane.showMessageDialog(this, "Employee addded successfully");
                    tf1.setText("");
                    tf2.setText("");
                    tf3.setText("");
                    tf4.setText("");

                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }


    }//GEN-LAST:event_btActionPerformed

    private void tf5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf5ActionPerformed

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed

        int ans = 0;

        JFileChooser jfc = new JFileChooser("C://");
        jfc.showOpenDialog(this);
        if (ans == JFileChooser.APPROVE_OPTION) {
            File f = jfc.getSelectedFile();
            tf5.setText(f.getPath());
            path = tf5.getText();
        }


    }//GEN-LAST:event_bt5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(project3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(project3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(project3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(project3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new project3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt;
    private javax.swing.JButton bt5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb23;
    private javax.swing.JLabel lb4;
    private javax.swing.JLabel lb5;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextField tf5;
    // End of variables declaration//GEN-END:variables
}
