
import java.sql.*;
import javax.swing.*;

public class project extends javax.swing.JFrame {

    /**
     * Creates new form project
     */
    public project() {
        
        
        initComponents();
        setSize(500,500); 
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        bt = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().setLayout(null);

        lb1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lb1.setForeground(new java.awt.Color(255, 255, 0));
        lb1.setText("ADMIN    LOGIN");
        getContentPane().add(lb1);
        lb1.setBounds(110, 10, 180, 60);

        lb2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lb2.setForeground(new java.awt.Color(255, 255, 0));
        lb2.setText("Username :");
        getContentPane().add(lb2);
        lb2.setBounds(60, 80, 80, 40);

        lb3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lb3.setForeground(new java.awt.Color(255, 255, 0));
        lb3.setText("Password :");
        getContentPane().add(lb3);
        lb3.setBounds(60, 140, 90, 40);

        tf1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        getContentPane().add(tf1);
        tf1.setBounds(190, 90, 170, 30);

        bt.setBackground(new java.awt.Color(255, 255, 255));
        bt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bt.setForeground(new java.awt.Color(51, 0, 51));
        bt.setText("LOGIN");
        bt.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(53, 255, 255)));
        bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActionPerformed(evt);
            }
        });
        getContentPane().add(bt);
        bt.setBounds(130, 240, 120, 40);

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(190, 140, 170, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decoration _snow.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 470, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActionPerformed
        String s1=tf1.getText();
        String s2=jPasswordField1.getText();
        if(s1.equals("")||s2.equals(""))
        {
            JOptionPane.showMessageDialog(this,"All fields are required");
        }
         
        else
        {
            try
            {
                Class.forName("com.mysql.jdbc.Driver");
                System.out.println("Driver loaded successfully.");
                Connection conn =DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/test","root","system27");
                System.out.println("Connection with DataBase successful");
                
                Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
                ResultSet rs=stmt.executeQuery("select * from admin where username = '"+s1+"' and password = '"+s2+"'");
                System.out.println("ResultSet created");
                if(rs.next())
                {
                    JOptionPane.showMessageDialog(this,"Login successful.");
                    tf1.setText("");
                    jPasswordField1.setText("");
                      new project2().setVisible(true);
                    this.dispose();
                    
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Login not successful.");
                    
                }
            } 
            catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btActionPerformed

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed

       
    }//GEN-LAST:event_tf1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new project().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JTextField tf1;
    // End of variables declaration//GEN-END:variables
}
