
import java.sql.*;

import javax.swing.table.*;
import javax.swing.*;

import java.util.*;

public class viewemp extends javax.swing.JFrame {

    ArrayList<emp> al = new ArrayList<>();

    mytablemodel tm;

    public viewemp() 
    {
        initComponents();
        setSize(600, 600);
        setTitle("View emp");
        tm = new mytablemodel();
        jt1.setModel(tm);
        getdata();
        pn.setVisible(false);

    }

    void getdata() {
        al.clear();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            System.out.println("Driver loaded");
            Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/test", "root", "system27");
            System.out.println("Connection with DataBase successful");

            Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            ResultSet rs = stmt.executeQuery("select * from employee ");

            while (rs.next()) {

                String Username = rs.getString("username");
                String Name = rs.getString("name");

                String Email = rs.getString("email");
                String Phone = rs.getString("phone");
                String Password = rs.getString("password");

                al.add(new emp(Username, Name, Email, Phone, Password));
            }
            tm.fireTableDataChanged();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }
//////////////////////////////////////////////

    class emp {

        String Username;
        String Name;
        String Email;
        String Phone;
        String Password;

        public emp(String Username, String Name, String Email, String Phone, String Password) {
            this.Username = Username;
            this.Name = Name;
            this.Email = Email;
            this.Phone = Phone;
            this.Password = Password;
        }

    }

    ////////////////////////////
    class mytablemodel extends AbstractTableModel {

        public int getRowCount() {
            return (al.size());

        }

        public int getColumnCount() {
            return 5;
        }

        public Object getValueAt(int i, int j) {
            emp emp = al.get(i);

            if (j == 0) {
                return emp.Username;

            } else if (j == 1) {
                return emp.Name;
            } else if (j == 2) {
                return emp.Email;
            } else if (j == 3) {
                return emp.Phone;
            } else {
                return emp.Password;
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt1 = new javax.swing.JTable();
        jbt2 = new javax.swing.JButton();
        jbt1 = new javax.swing.JButton();
        pn = new javax.swing.JPanel();
        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        lb4 = new javax.swing.JLabel();
        lb5 = new javax.swing.JLabel();
        bt3 = new javax.swing.JButton();
        tf1 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        tf3 = new javax.swing.JTextField();
        tf4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jLabel3.setText("USERNAME");

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jt1.setBackground(new java.awt.Color(204, 255, 255));
        jt1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204), 2));
        jt1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jt1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "username", "name", "email", "phone", "password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jt1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 30, 350, 300);

        jbt2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jbt2.setForeground(new java.awt.Color(0, 0, 204));
        jbt2.setText("EDIT");
        jbt2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(53, 255, 255)));
        jbt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbt2);
        jbt2.setBounds(180, 370, 120, 50);

        jbt1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jbt1.setForeground(new java.awt.Color(0, 0, 204));
        jbt1.setText("DELETE");
        jbt1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(53, 255, 255)));
        jbt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbt1);
        jbt1.setBounds(30, 370, 120, 50);

        pn.setBackground(new java.awt.Color(204, 255, 255));
        pn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        pn.setLayout(null);

        lb1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lb1.setText("     EDIT INFO");
        pn.add(lb1);
        lb1.setBounds(70, 10, 110, 40);

        lb2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb2.setText("Username");
        pn.add(lb2);
        lb2.setBounds(10, 70, 80, 30);

        lb3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb3.setText("Name");
        pn.add(lb3);
        lb3.setBounds(10, 110, 80, 30);

        lb4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb4.setText("Email");
        pn.add(lb4);
        lb4.setBounds(10, 150, 80, 30);

        lb5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lb5.setText("Phone");
        pn.add(lb5);
        lb5.setBounds(10, 190, 70, 30);

        bt3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        bt3.setText("Update");
        bt3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 204)));
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });
        pn.add(bt3);
        bt3.setBounds(80, 280, 100, 30);

        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        pn.add(tf1);
        tf1.setBounds(90, 70, 150, 30);

        tf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf2ActionPerformed(evt);
            }
        });
        pn.add(tf2);
        tf2.setBounds(90, 110, 150, 30);

        tf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf3ActionPerformed(evt);
            }
        });
        pn.add(tf3);
        tf3.setBounds(90, 150, 150, 30);
        pn.add(tf4);
        tf4.setBounds(90, 190, 150, 30);

        getContentPane().add(pn);
        pn.setBounds(380, 30, 280, 340);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yellow-umbrella_1434_990x742.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 670, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt1ActionPerformed
        if (jt1.getSelectedRow() == -1) 
        
        {
            JOptionPane.showMessageDialog(this, "Select Row");
        } 
        else
        {
            String s = al.get(jt1.getSelectedRow()).Username;
            try {
              
                
                Class.forName("com.mysql.jdbc.Driver");
                System.out.println("Driver loaded");
                Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/test", "root", "system27");
                System.out.println("Connection with DataBase successful");

                Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                ResultSet rs = stmt.executeQuery("select * from employee where username='" + s + "'");

                if (rs.next()) {
                    rs.deleteRow();

                    

                }
                getdata();
            } catch (Exception e)
            {
                e.printStackTrace();
            }

        }


    }//GEN-LAST:event_jbt1ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        // TODO add yo
      
        String s = al.get(jt1.getSelectedRow()).Username;
         String Name=tf2.getText();
          String Email=tf3.getText();
           String Phone=tf4.getText();
           try
           {
               
           
             Class.forName("com.mysql.jdbc.Driver");
                System.out.println("Driver loaded");
                Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/test", "root", "system27");
                System.out.println("Connection with DataBase successful");

                Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                ResultSet rs = stmt.executeQuery("select * from employee where username ='"+s+"'");
                if(rs.next())
                {
                   rs.updateString("name",Name);
                   rs.updateString("email",Email);
                   rs.updateString("phone",Phone);
                   
                   rs.updateRow();
                  
                }
                 getdata();
                 pn.setVisible(false);
                 
           }      
           catch(Exception ex)
                   {
                       ex.printStackTrace();
                   }
    }//GEN-LAST:event_bt3ActionPerformed

    private void tf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf3ActionPerformed

    private void tf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf2ActionPerformed

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    private void jbt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt2ActionPerformed

        
if(jt1.getSelectedRow()==-1)
{
    JOptionPane.showMessageDialog(this,"add entries to update");
    
}
else
{
    pn.setVisible(true);
    String  s1=al.get(jt1.getSelectedRow()).Username;
    String  s2=al.get(jt1.getSelectedRow()).Name;
    String  s3=al.get(jt1.getSelectedRow()).Email;
    String  s4=al.get(jt1.getSelectedRow()).Phone;
    
    tf1.setText(s1);   
    tf2.setText(s2);
    tf3.setText(s3);
    tf4.setText(s4);
tf1.setEditable(false);
}


    
    








// TODO add your handling code here:
    }//GEN-LAST:event_jbt2ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewemp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbt1;
    private javax.swing.JButton jbt2;
    private javax.swing.JTable jt1;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JLabel lb5;
    private javax.swing.JPanel pn;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    // End of variables declaration//GEN-END:variables
}
